version: '3'
services:
  student_db:
    image: postgres
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_USER=student
      - POSTGRES_PASSWORD=student
      - POSTGRES_DB=student
    volumes:
      - ./.docker/data:/var/lib/postgresql/data